<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T3/semana-02/blob/main/Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns  # Biblioteca de visualização que possui datasets de estudo embutidos
import kagglehub

In [ ]:
print("1. Carregando o dataset de estudo diretamente da biblioteca...")

# O método 'load_dataset' traz os dados prontos para uso em formato de tabela
#df = sns.load_dataset('iris')
# df = pd.read_excel('dengue_dados.xlsx')

df = pd.read_csv('dengue_dados.csv')

1. Carregando o dataset de estudo diretamente da biblioteca...

In [ ]:
print("\n--- VISÃO GERAL DOS DADOS ---")
display(df.head(200))

--- VISÃO GERAL DOS DADOS ---

   Idade Sexo  Peso   Manchas  Temp  Num.Inter. Estado Diagnóstico
0     37    M    73   Grandes  38.0           2     SP      Doente
1     18    F    79  Pequenas  39.5           4     MG    Saudável
2     40    M    68  Pequenas  38.0           0     RS      Doente
3     18    F    90    Médias  38.5          11     MG      Doente
4     50    M    78   Grandes  37.6           2     PE    Saudável
5     54    M    56  Pequenas  38.0           3     RJ    Saudável
6     72    M    67   Grandes  39.0           0     AM      Doente
7     22    M    78    Médias  38.4           6     GO    Saudável

In [ ]:
print("\n2. Separando as Features (X) e o Rótulo (y)...")
# Queremos prever a especie flor
X = df.drop(columns=['Diagnóstico'])

2. Separando as Features (X) e o Rótulo (y)...

In [ ]:
print(X)

   Idade Sexo  Peso   Manchas  Temp  Num.Inter. Estado
0     37    M    73   Grandes  38.0           2     SP
1     18    F    79  Pequenas  39.5           4     MG
2     40    M    68  Pequenas  38.0           0     RS
3     18    F    90    Médias  38.5          11     MG
4     50    M    78   Grandes  37.6           2     PE
5     54    M    56  Pequenas  38.0           3     RJ
6     72    M    67   Grandes  39.0           0     AM
7     22    M    78    Médias  38.4           6     GO

In [ ]:
# y = Apenas a coluna 'tip' (Nosso gabarito)
y = df['Diagnóstico']

In [ ]:
print(y)

0      Doente
1    Saudável
2      Doente
3      Doente
4    Saudável
5    Saudável
6      Doente
7    Saudável
Name: Diagnóstico, dtype: object

In [ ]:
print("\n--- AS FEATURES (X) ---")
display(X.head(3))

--- AS FEATURES (X) ---

   Idade Sexo  Peso   Manchas  Temp  Num.Inter. Estado
0     37    M    73   Grandes  38.0           2     SP
1     18    F    79  Pequenas  39.5           4     MG
2     40    M    68  Pequenas  38.0           0     RS

In [ ]:
print("\n--- O RÓTULO (y) ---")
display(y.head(3))

--- O RÓTULO (y) ---

0      Doente
1    Saudável
2      Doente
Name: Diagnóstico, dtype: object